### ISSUE TITLE
Takes too much time to add Constraints.

### ISSUE THREAD

**Issue by thakkar111** [EmbersArc/Epigraph#2]
Hi,

I am using the QP solver of this library for my application. I Have almost 1000 variables in my actual application and it was taking too much time to add EqualTo constraint. I was not sure if it got stuck somewhere, so I started again with 320 variables with a similar EqualTo constraint. I realized that solver is working but it is taking too much time, more than an hour to add cost function and constraints. I am not sure if I am missing something over here or is it normal for this library to take this much amount of time?

Thank you.

**Comment by EmbersArc** [comment]
Hey, thanks for the report. I remember having this problem earlier in development and thought it had gone away.

It would be really helpful if you could provide a piece of code that has this issue so that I can track down the problem more easily.

**Comment by thakkar111** [comment]
Hi, Thank you so much for your prompt response. Yes, I am sharing a piece of code from cpp file over here. Although, it is pretty long it is just the parameter definition. And later in the last few lines, I am implementing the Solver. I have not included the cost function over here as the definition of those matrices is even longer. But please let me know if you want to have a look over them too. 


`    Id2 = MatrixXd::Identity(2,2); // 2x2 Identity Matrix
    Zr2 = MatrixXd::Zero(2,2); // 2x2 Zero/Null Matrix
    Zr102 = MatrixXd::Zero(10,2); // 10x2 Zero/Null Matrix
    N = 16;
    n = 80; 
  

    // Definition of Actual State Space Matrices
    MatrixXd Aeq(10,10);
    Aeq << Id2, dt*Id2, Zr2, dt2/2*Id2, Zr2,
           Zr2, Id2, Zr2, dt*Id2, Zr2,
           Zr2, Zr2, Id2, Zr2, dt*Id2,
           Zr2, Zr2, Zr2, Id2, Zr2,
           Zr2, Zr2, Zr2, Zr2, Id2;

    MatrixXd Beq(10,4);
    Beq << dt3/6*Id2, Zr2,
           dt2/2*Id2, Zr2,
           Zr2, dt2/2*Id2,
           dt*Id2, Zr2,
           Zr2, dt*Id2;

    // Definition of Augmented State Space Matrices
    MatrixXd Atelda(12,12);
    Atelda << Id2, Ceq*Aeq,
              Zr102, Aeq;

    MatrixXd Btelda(12,4);
    Btelda << Ceq*Beq,
              Beq;

    Qe = MatrixXd:: Identity(2,2); // Penalty Matrix for Variation in ZMP i.e Delta P
    e1 = Qe.rows();  
    e2 = Qe.cols(); 
    qx = 0;     
    lambda = 10; //  Penalty for Hx adn Hy
    Qx = MatrixXd::Zero(10,10);
    Qx.diagonal() << qx, qx, qx, qx, lambda, lambda, qx, qx, qx, qx; 
    x1 = Qx.rows(); 
    x2 = Qx.cols(); 
    R = 1e-6*MatrixXd::Identity(4,4);// Penalty Matrix for difference in consecutive values of u i.e (cdddotx, cdddoty, Hddotx, Hddoty)
    r1 = R.rows ();  
    r2 = R.cols ();  

    // Writing down the Constraint Matrix
    A = MatrixXd::Zero((e1+x1)*(n-1), N*n);
    for (int i = 0; i < n-1; i++){
        for (int j = 0; j < e1+x1; j++){
            A((e1+x1)*i+j, (i+1)*N+j) = 1;
            for (int k = 0; k < e1+x1; k++){
                A((e1+x1)*i+j, i*N+k) = -1*Atelda(j,k);
            }
            for (int l = 0; l < r1; l++){
                A((e1+x1)*i+j, i*N+e1+x1+l) = -1*Btelda(j,l);
            }
        }
    }
  
    // RHS Matrix of the Constraints
    b = MatrixXd::Zero((e1+x1)*(n-1),1);

    //Formulate QP.
    OptimizationProblem qp;
    
    // Declare variables to be optimized 
    VectorX x = qp.addVariable("x", N*n); // Total number of varibale to be optimized are N*n
    
    // Add constraints Ax = b
    qp.addConstraint(equalTo(par(A) * x, par(b)));`

**Comment by EmbersArc** [comment]
Ah, I see. I changed the code a bit to get an idea of what is happening:

```
#include "epigraph.hpp"

#include <fmt/format.h>
#include <fmt/ostream.h>

using namespace cvx;
using namespace Eigen;

int main()
{

    int N = 16;
    int n = 80;

    // Definition of Actual State Space Matrices
    // MatrixXd Aeq(10,10);
    // Aeq << Id2, dt*Id2, Zr2, dt2/2*Id2, Zr2,
    //        Zr2, Id2, Zr2, dt*Id2, Zr2,
    //        Zr2, Zr2, Id2, Zr2, dt*Id2,
    //        Zr2, Zr2, Zr2, Id2, Zr2,
    //        Zr2, Zr2, Zr2, Zr2, Id2;

    // MatrixXd Beq(10,4);
    // Beq << dt3/6*Id2, Zr2,
    //        dt2/2*Id2, Zr2,
    //        Zr2, dt2/2*Id2,
    //        dt*Id2, Zr2,
    //        Zr2, dt*Id2;

    // Definition of Augmented State Space Matrices
    MatrixXd Atelda(12, 12);
    Atelda.setRandom();
    // Atelda << Id2, Ceq*Aeq,
    //           Zr102, Aeq;

    MatrixXd Btelda(12, 4);
    // Btelda << Ceq*Beq,
    //           Beq;
    Btelda.setRandom();

    MatrixXd Qe = MatrixXd::Identity(2, 2); // Penalty Matrix for Variation in ZMP i.e Delta P
    int e1 = Qe.rows();
    int e2 = Qe.cols();
    int qx = 0;
    int lambda = 10; //  Penalty for Hx adn Hy
    MatrixXd Qx = MatrixXd::Random(10, 10);
    Qx.diagonal() << qx, qx, qx, qx, lambda, lambda, qx, qx, qx, qx;
    int x1 = Qx.rows();
    int x2 = Qx.cols();
    MatrixXd R = 1e-6 * MatrixXd::Identity(4, 4); // Penalty Matrix for difference in consecutive values of u i.e (cdddotx, cdddoty, Hddotx, Hddoty)
    int r1 = R.rows();
    int r2 = R.cols();

    // Writing down the Constraint Matrix
    MatrixXd A = MatrixXd::Zero((e1 + x1) * (n - 1), N * n);
    for (int i = 0; i < n - 1; i++)
    {
        for (int j = 0; j < e1 + x1; j++)
        {
            A((e1 + x1) * i + j, (i + 1) * N + j) = 1;
            for (int k = 0; k < e1 + x1; k++)
            {
                A((e1 + x1) * i + j, i * N + k) = -1 * Atelda(j, k);
            }
            for (int l = 0; l < r1; l++)
            {
                A((e1 + x1) * i + j, i * N + e1 + x1 + l) = -1 * Btelda(j, l);
            }
        }
    }

    // RHS Matrix of the Constraints
    MatrixXd b = MatrixXd::Zero((e1 + x1) * (n - 1), 1);

    //Formulate QP.
    OptimizationProblem qp;

    // Declare variables to be optimized
    VectorX x = qp.addVariable("x", N * n); // Total number of varibale to be optimized are N*n

    // This shows a lot of zeros
    fmt::print("{}\n", A);

    // Add constraints Ax = b
    qp.addConstraint(equalTo(par(A) * x, par(b)));
}
```

When I print out A it becomes obvious that it is extremely sparse. The latest version of Epigraph also supports sparse matrices so this works:

```
    Eigen::SparseMatrix<double> sparseA = A.sparseView();

    // Add constraints Ax = b
    auto equality = equalTo(par(sparseA) * x, par(b));
    qp.addConstraint(equality);
```

This reduces the number of values in A from 1'213'440 to 16'116. Now this alone does not seem to solve the issue. It still takes ages. While experimenting I found that this is lightning fast:

```
    // Add constraints Ax = b
    MatrixX Ax = par(sparseA) * x;
    auto equality = equalTo(Ax, par(b));
    qp.addConstraint(equality);
```

So I can't give you a reason why this is yet, but at least you now have a fast solution. But this is a very interesting case and I will keep investigating. Thanks for bringing it to my attention!

Also, I'm not exactly sure what is happening in the nested loops that fill in A, but I feel like it might be something that can be replaced by just formulating the constraints one by one instead of doing it in one go with a very sparse A matrix. That's what the library is for ;) Let me know if you find a solution there.

**Comment by EmbersArc** [comment]
Okay, the problem is two-fold:

1. This is very slow since it is a multiplication with a very large matrix:
```
VectorX Ax = par(A) * x;
```
And can be fixed by using a sparse matrix:
```
Eigen::SparseMatrix<double> sparseA = A.sparseView();
VectorX Ax = par(sparseA) * x;
```
I recommend you start building the sparse matrix with triplets as documented [here](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html), instead of first constructing a dense matrix.

2. This is very slow as well, but for a completely different reason:
```
equalTo(par(sparseA) * x, par(b));
```
Here, the left hand side is of type `const Eigen::Product<Eigen::SparseMatrix<cvx::Scalar, 0, int>, cvx::VectorX, 0>` which does not implicitly evaluate to a dense `VectorX`. The function `equalTo()` then uses coefficient-wise access, which is very slow on this type since it involves a binary search. Therefore, either of these options is much faster:
```
VectorX Ax = par(sparseA) * x;
equalTo(Ax, par(b));
// or
equalTo((par(sparseA) * x).eval(), par(b));
```

The obvious fix for this would be to explicitly convert the inputs inside the constraint functions, but I'll try to find a more elegant way to work around this issue.

Let me know if you have any other questions or if there's anything else that doesn't work as expected.

**Comment by thakkar111** [comment]
I really appreciate your quick response and enthusiasm in fixing this issue. I have earlier implemented this in Matlab and I was trying to formulate the problem similarly. That's how I stumbled upon this kind of formulation. But, now I do realize and understand how to work around while working with Eigen. I have implemented the problem with the first approach and now it is lightning fast as you mentioned compared to what I was doing. I will now try to build a sparse matrix with triplets as you have suggested.  

However, while I ran the code after fixing it with the first method I ended up with one more problem. Although it is not relevant to this one. The cost function in my case has both quadratic and linear terms i.e xT*0.5H*x + fT*x. I want to highlight 2 points over here, which I encountered. 

1. When I add linear cost term i.e fT*x I get the error during the solver initialization i.e `osqp::OSQPSolver solver(qp);`. The error message is this,

terminate called after throwing an instance of 'std::runtime_error'
 what():  Variable must be linked to a problem first!
Aborted (core dumped)

I have tried scrutinizing the scalar quantity which this term leads to and it is similar to the one in the examples provided in the library. So, it is getting a bit difficult to figure out it with this error message. 

2. Then I tried optimizing the problem just using quadratic terms. In this case, the problem gets solved but Solution Polish remains unsuccessful. I would appreciate if you can share some guidance over this point, too.

**Comment by EmbersArc** [comment]
Glad I could help. Beta testers are highly appreciated!

And the description of your second problem was already enough to track down the issue. I've pushed a fix to master, it should work now.

Unfortunately I can't help you with the failed polish since I don't know enough about OSQP to tell where it might come from. Maybe with the linear part it works out fine, let me know.

**Comment by thakkar111** [comment]
Thank you so much for all your help. It is working perfectly fine. Even Polish has started working.
